x = int(input("Введите число:x"))
a = int(input("Введите число:a"))
b = int(input("Введите число:b"))
c = int(input("Введите число:c"))
R = int(input("Введите число:R"))
d = int(input("Введите число:d"))

print(f"а)
print(f"а)
print(f"а)
print(f"а)
print(f"а)
print(f"а)
print(f"а)
print(f"а)
print(f"а)
